# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20190623_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
